### ISSUE TITLE
Typescript problem useQueryState<string> with only one argument (says it expects 2 arguments)

### ISSUE THREAD

**Issue by jrhoads** [47ng/next-usequerystate#289]
First.  Thank you for your work on this project.
Second: I am fairly new to Typescript and React, so I may be missing something (or a lot of somethings).

I have a problem and I think I may have tracked it down.
I am working on a nextjs project that uses typescript and your excellent library

I have several places where I use `useQueryState` with only one argument
(ex. `const [searchQuery] = useQueryState<string>('query')`)
(ex. with context https://github.com/datacite/akita/blob/714921b8f6aa340867c0314e62f69538e722318d/src/pages/repositories/index.tsx#L10)

I get a problem in `next build` and `tsc` when I use version >1.5.0
(I don't have a problem when I use `next dev` and run my CI tests.  Only when I build)

I get an error that says 
```error TS2554: Expected 2 arguments, but got 1.
const [searchQuery] = useQueryState<string>('query')
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/next-usequerystate/dist/types/useQueryState.d.ts:39:55
    39 export declare function useQueryState<T>(key: string, options: UseQueryStateOptions<T> & {
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    40     defaultValue: T;
       ~~~~~~~~~~~~~~~~~~~~
    41 }): UseQueryStateReturn<NonNullable<ReturnType<typeof options.parse>>, typeof options.defaultValue>;
       ~
    An argument for 'options' was not provided.
```

There was a commit as part of the work going from 1.5.0 to 1.6.0 and thus carried through to 1.7.0.  Specifically  "[5cb4441](https://github.com/47ng/next-usequerystate/commit/5cb4441eddf6cf53d897cf01d05632bcf0fc1381#diff-7dd47c9b1097d36e7b94e27a404704c0d026a9c5ac9a62509715f357f4bc8b7aL96)" around old line 96 that removed the `options?` argument in the function call.  I think this may be why I'm seeing errors thrown in the build process.

Seems like it might have been an error in the commit among the large amount of great work that commit contains.

Am I on the right track?

Again.  Thanks for your work.

**Comment by franky47** [comment]
Can I have a look at your tsconfig.json?

**Comment by jrhoads** [comment]
Sure.  Thanks for taking a look.

https://github.com/datacite/akita/blob/714921b8f6aa340867c0314e62f69538e722318d/tsconfig.json

I admit that I'm not 100% sure what all of it does.

**Comment by franky47** [comment]
I updated my comment since I posted it, you should be able to fix it with removing the explicit `<string>` type cast on the hook. It throws the compiler off-course in finding the right overload to use. Since string queries are the default, it's not needed.

The fact that you didn't see the error sooner could be because you have `"strict": false` in your TS config, but if you're just getting started it's probably better to keep it that way (unless you like being yelled at by the TS compiler 😅).

Some great resources to learn more about TypeScript:
- Stefan Baumgartner's [blog](https://fettblog.eu/) 
- Marius Schulz's [TypeScript Evolution](https://mariusschulz.com/blog/series/typescript-evolution) series

**Comment by jrhoads** [comment]
Thank you for pointing me towards removing the explicit `<string>` type cast.  That worked like a charm.

Also thank you for pointing me towards those resources.  I'm digging through them now.

I'll go ahead and close this issue.  Thanks again for your guidance.
