### ISSUE TITLE
Support for Next App Router (version 13.4)

### ISSUE THREAD

**Issue by andreisocaciu** [47ng/next-usequerystate#327]
Hi, 

I use this library in my own projects and I was curious if there are any plans to add support for the new `app` directory that is now stable in [Next 13.4](https://nextjs.org/blog/next-13-4).

The main issue is that the `useRouter` from `'next/router'` is no longer supported in the `app` directory and it makes using this library impossible. It is being replaced by the `useRouter` from `'next/navigation'`, together with `usePathname` and `useSearchParams`.

**Comment by franky47** [comment]
Eventually, yes, though I suppose this will require a major version bump because of the breaking changes you mention, or some sort of dual export to target either the pages or app routers.

That being said, with Next.js becoming more and more of a server-first framework, I expect a lot of hurdles along the way.

If you'd like to open a PR, I will gladly review it.
